// CardDefenseTable.h -- generated by Ursa-Server/tools/gen-card-defense-table.ps1. DO NOT EDIT.
//
// Monster card defense data for the client plugin: itemId -> resistance letter(s) + percentage,
// taken from Item.wz/Consume/0238.img.xml (spec/defenseAtt, spec/defenseState, spec/prob).
//
// attLetter   : elemental resistance letter as stored by the client ('I','F','L','S'; space = none)
// stateLetter : state resistance letter ('D','C'; space = none) -- consumer not implemented yet
// percent     : damage reduction percentage (positive; the client divides by -100)
//
// Rows are sorted by itemId; lookup is a binary search.
#pragma once

struct CardDefenseEntry {
    int itemId;
    char attLetter;
    char stateLetter;
    int percent;
};

static const CardDefenseEntry kCardDefenseTable[] = {
    { 2382003, 'F', ' ', 4 },
    { 2382011, 'F', ' ', 3 },
    { 2382012, 'L', ' ', 3 },
    { 2382013, 'I', ' ', 3 },
    { 2382018, 'S', ' ', 3 },
    { 2382021, ' ', 'C', 5 },
    { 2382024, 'S', ' ', 3 },
    { 2382036, 'S', ' ', 3 },
    { 2382039, 'I', ' ', 3 },
    { 2382044, 'S', ' ', 3 },
    { 2382048, 'L', ' ', 3 },
    { 2382056, 'I', ' ', 3 },
    { 2382059, 'L', ' ', 3 },
    { 2382062, 'L', ' ', 3 },
    { 2383017, 'F', ' ', 6 },
    { 2383021, 'F', ' ', 6 },
    { 2383022, 'L', ' ', 6 },
    { 2383023, 'I', ' ', 6 },
    { 2383024, ' ', 'F', 10 },
    { 2383028, 'L', ' ', 6 },
    { 2383034, ' ', 'C', 10 },
    { 2383037, 'S', ' ', 6 },
    { 2383038, 'S', ' ', 6 },
    { 2383042, 'L', ' ', 6 },
    { 2383044, 'F', ' ', 6 },
    { 2383047, ' ', 'W', 10 },
    { 2384005, ' ', 'D', 15 },
    { 2384006, 'I', ' ', 9 },
    { 2384008, ' ', 'F', 15 },
    { 2384009, 'I', ' ', 9 },
    { 2384010, ' ', 'S', 15 },
    { 2384015, ' ', 'D', 15 },
    { 2384016, 'I', ' ', 9 },
    { 2384020, 'S', ' ', 9 },
    { 2384021, 'F', ' ', 9 },
    { 2384022, 'I', ' ', 9 },
    { 2384023, 'S', ' ', 9 },
    { 2384024, ' ', 'C', 15 },
    { 2384028, 'S', ' ', 9 },
    { 2384030, ' ', 'D', 15 },
    { 2384033, ' ', 'C', 15 },
    { 2384037, 'I', ' ', 9 },
    { 2385016, ' ', 'D', 20 },
    { 2385017, 'F', ' ', 12 },
    { 2385018, 'I', ' ', 12 },
    { 2385021, 'F', ' ', 12 },
    { 2386002, 'F', ' ', 15 },
    { 2386003, ' ', 'D', 25 },
    { 2386004, 'I', ' ', 15 },
    { 2386007, ' ', 'D', 25 },
    { 2386008, 'F', ' ', 15 },
    { 2386009, 'F', ' ', 15 },
    { 2386010, 'I', ' ', 15 },
    { 2386012, 'I', ' ', 15 },
    { 2386013, 'I', ' ', 15 },
    { 2386015, ' ', 'D', 25 },
};

static const int kCardDefenseTableCount = 56;

// Returns the entry for a monster card item id, or 0 when the id is not a defense card.
inline const CardDefenseEntry* CardDefense_Find(int itemId) {
    int lo = 0;
    int hi = kCardDefenseTableCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (kCardDefenseTable[mid].itemId == itemId) {
            return &kCardDefenseTable[mid];
        }
        if (kCardDefenseTable[mid].itemId < itemId) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return 0;
}

// Element code used by the client's CalcBuffDefenseAttr (1=I, 2=F, 3=L, 4=S) -> letter, or 0.
inline char CardDefense_ElementLetter(int element) {
    switch (element) {
        case 1: return 'I';
        case 2: return 'F';
        case 3: return 'L';
        case 4: return 'S';
        default: return 0;
    }
}