// Pet auto-buff skill whitelist -- GENERATED by Ursa-Server tools/gen-petbuff-whitelist.ps1.
// Do not edit by hand: re-run the generator instead.
//
// Source of truth: BeiDou-Server client/SkillFactory.java loadFromData isBuff=true table
// (the same block tools/gen-isbuff-tables.ps1 reads for the server side).
// Riding skills are excluded (4 of them): StatEffect.applyBuffEffect :1298/:1327
// replaces the buff id with the mount item id inside isMonsterRiding(), so buffid != skillId there.
//
// Only these skill ids may be dropped into a pet auto-buff slot, and only a buff whose
// client temporary-stat entry is nType == 2 && nID == skillId counts as "this skill is up".
#pragma once

// Sorted ascending. 182 entries.
static const int kPetBuffSkillIds[] = {
    100, 1001, 1002, 1005, 1001003, 1101004, 1101005, 1101006,
    1101007, 1111002, 1111007, 1121000, 1121002, 1121010, 1121011, 1201004,
    1201005, 1201006, 1201007, 1211003, 1211004, 1211005, 1211006, 1211007,
    1211008, 1211009, 1221000, 1221002, 1221003, 1221004, 1221012, 1301004,
    1301005, 1301006, 1301007, 1311007, 1311008, 1320008, 1320009, 1321000,
    1321002, 1321007, 1321010, 2001002, 2001003, 2101001, 2101003, 2111004,
    2111005, 2121000, 2121002, 2121004, 2121008, 2201001, 2201003, 2211004,
    2211005, 2221000, 2221002, 2221004, 2221008, 2301003, 2301004, 2311001,
    2311002, 2311003, 2311005, 2321000, 2321002, 2321004, 2321005, 2321009,
    3001003, 3101002, 3101004, 3111002, 3121000, 3121002, 3121008, 3121009,
    3201002, 3201004, 3211002, 3221000, 3221002, 3221006, 3221008, 4001003,
    4101003, 4101004, 4111001, 4111002, 4121000, 4121004, 4121006, 4121009,
    4201002, 4201003, 4211003, 4211005, 4221000, 4221004, 4221008, 5001005,
    5111005, 5121003, 5221010, 9001004, 9101001, 9101002, 9101003, 9101004,
    9101008, 10000012, 10000100, 10001001, 10001002, 10001005, 11001001, 11001004,
    11101001, 11101002, 11101003, 11111001, 11111007, 12001001, 12001002, 12001004,
    12101000, 12101001, 12101004, 12101005, 12111002, 12111004, 13001002, 13001004,
    13101001, 13101002, 13101003, 13101006, 13111004, 13111005, 14001003, 14001005,
    14101002, 14101003, 14111000, 15001003, 15001004, 15100004, 15101002, 15101006,
    15111001, 15111002, 15111005, 15111006, 20000012, 20000100, 20001001, 20001002,
    20001005, 20010012, 20011001, 20011002, 20011005, 21000000, 21001003, 21100005,
    21101003, 21111001, 21111005, 21120007, 21121000, 21121008, 22111001, 22121001,
    22131001, 22141002, 22141003, 22151003, 22171000, 22171004,
};
static const int kPetBuffSkillCount = 182;

// True when skillId is a buff skill that may be auto-refreshed.
inline bool IsPetBuffSkill(int skillId)
{
    int lo = 0, hi = kPetBuffSkillCount - 1;
    while (lo <= hi)
    {
        const int mid = lo + ((hi - lo) >> 1);
        const int v = kPetBuffSkillIds[mid];
        if (v == skillId) return true;
        if (v < skillId) lo = mid + 1; else hi = mid - 1;
    }
    return false;
}

// Summon skills (subset of the list above). These are the ids StatEffect.getSummonMovementType
// (:1781-1812) answers non-null for, i.e. the ones the server will spawn a summon entity for
// (applyTo :1056 `summonMovementType != null && pos != null`). A summon cast carries its spawn
// point where a plain buff carries the tDelay short -- CUserLocal::DoActiveSkill sends 1321007
// through its own summon arm (sub_96B140): Encode2(x) Encode2(y) Encode1(facing), five bytes
// after the level byte, which is exactly what SpecialMoveHandler.java:134-136 reads a point from
// (`p.available() == 5`). A silent cast without those five bytes still applies the buff, but the
// summon never appears.
// Sorted ascending. 10 entries.
static const int kPetBuffSummonSkillIds[] = {
    1321007, 3111002, 3211002, 11001004, 12001004, 12111004, 13001004, 13111004,
    14001005, 15001004,
};
static const int kPetBuffSummonSkillCount = 10;

// True when skillId is one of the whitelisted summon skills, i.e. one whose cast must carry the
// spawn point so the server creates the summon entity.
inline bool IsPetBuffSummonSkill(int skillId)
{
    int lo = 0, hi = kPetBuffSummonSkillCount - 1;
    while (lo <= hi)
    {
        const int mid = lo + ((hi - lo) >> 1);
        const int v = kPetBuffSummonSkillIds[mid];
        if (v == skillId) return true;
        if (v < skillId) lo = mid + 1; else hi = mid - 1;
    }
    return false;
}
